CREATE DATABASE APPLICATION;
CREATE SCHEMA FURTHER_ADVANCE;
CREATE SEQUENCE FURTHER_ADVANCE.app_id_seq
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NO MAXVALUE
  CACHE 1;
CREATE TABLE FURTHER_ADVANCE.APP_ID (
    ID              INT PRIMARY KEY  NOT NULL,
	CASE_ID         INT              NOT NULL,
	ACCOUNT_NUMBER  INT              NOT NULL
);
CREATE TABLE FURTHER_ADVANCE.user_test (
    ID              INT PRIMARY KEY  NOT NULL,
	test         VARCHAR              NOT NULL,
	INFO            JSON              NOT NULL
);
ALTER TABLE FURTHER_ADVANCE.APP_ID ALTER COLUMN ID SET DEFAULT nextval('app_id_seq');